# Generated by Django 4.1.5 on 2023-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isDepartment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
