# Generated by Django 4.1.5 on 2023-02-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HallRecords', '0003_booking_user_rename_eventdetails_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
