# Generated by Django 4.1.7 on 2023-02-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
